authors:
  sujan:
    name: Sujan Parajuli, GISP
    description: Founder, GEE-O-Spatial Solutions
    avatar: https://github.com/SujanParajuli-GISP.png
    url: https://github.com/SujanParajuli-GISP
